version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    networks: ["vnet"]
    hostname: zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 1 3

  zookeeper-2:
    container_name: zookeeper-2    
    networks: ["vnet"]
    hostname: zookeeper-2.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 2 3

  zookeeper-3:
    container_name: zookeeper-3    
    networks: ["vnet"]
    hostname: zookeeper-3.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 3 3

  journalnode-1:
    container_name: journalnode-1
    networks: ["vnet"]
    hostname: journalnode-1.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      
    command: journalnode

  journalnode-2:
    container_name: journalnode-2
    networks: ["vnet"]
    hostname: journalnode-2.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      
    command: journalnode

  journalnode-3:
    container_name: journalnode-3
    networks: ["vnet"]
    hostname: journalnode-3.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      
    command: journalnode

  namenode-1:
    container_name: namenode-1
    networks: ["vnet"]
    hostname: namenode-1.vnet
    image: smizy/hadoop-base:2.7.2-alpine 
    expose: ["50070"]
    ports:  ["8020"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      
    entrypoint: entrypoint.sh
    command: namenode-1

  namenode-2:
    container_name: namenode-2
    networks: ["vnet"]
    hostname: namenode-2.vnet
    image: smizy/hadoop-base:2.7.2-alpine 
    expose: ["50070"]
    ports:  ["8020"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      
    entrypoint: entrypoint.sh
    command: namenode-2

  datanode-1:
    container_name: datanode-1
    networks: ["vnet"]
    hostname: datanode-1.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-2:
    container_name: datanode-2
    networks: ["vnet"]
    hostname: datanode-2.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-3:
    container_name: datanode-3
    networks: ["vnet"]
    hostname: datanode-3.vnet
    image: smizy/hadoop-base:2.7.2-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      
    entrypoint: entrypoint.sh
    command: datanode

  hmaster-1:
    container_name: hmaster-1
    networks: ["vnet"]
    hostname: hmaster-1.vnet
    image: smizy/hbase:1.1.5-alpine
    expose: [16000, 16010]
    environment:
      - SERVICE_16000_NAME=hmaster
      - SERVICE_16010_IGNORE=true
      
    volumes_from:
      - namenode-1
    command: hmaster-1

  hmaster-2:
    container_name: hmaster-2
    networks: ["vnet"]
    hostname: hmaster-2.vnet
    image: smizy/hbase:1.1.5-alpine
    expose: [16000, 16010]
    environment:
      - SERVICE_16000_NAME=hmaster
      - SERVICE_16010_IGNORE=true
      
    volumes_from:
      - namenode-2
    command: hmaster-2

  regionserver-1:
    container_name: regionserver-1
    networks: ["vnet"]
    hostname: regionserver-1.vnet
    image: smizy/hbase:1.1.5-alpine
    expose: [16020, 16030]
    environment:
      - SERVICE_16020_NAME=regionserver
      - SERVICE_16030_IGNORE=true
      
    command: regionserver

  regionserver-2:
    container_name: regionserver-2
    networks: ["vnet"]
    hostname: regionserver-2.vnet
    image: smizy/hbase:1.1.5-alpine
    expose: [16020, 16030]
    environment:
      - SERVICE_16020_NAME=regionserver
      - SERVICE_16030_IGNORE=true
      
    command: regionserver

  regionserver-3:
    container_name: regionserver-3
    networks: ["vnet"]
    hostname: regionserver-3.vnet
    image: smizy/hbase:1.1.5-alpine
    expose: [16020, 16030]
    environment:
      - SERVICE_16020_NAME=regionserver
      - SERVICE_16030_IGNORE=true
      
    command: regionserver

networks:
  vnet:
    external:
      name: vnet 
